### PR TITLE
stopping video stream and scan timeout + build instructions for Grunt

### PR DESCRIPTION
**Pull request by OACDesigns**
- added ability to stop video stream and cancel scan timeouts
- added grunt file for building minified versions
- added documentation for above

### CODE REVIEW

**Comment by dwa012** [comment]
Thanks for the changes. Merging them in.

**Comment by dwa012** [comment]
Merged in.

**Comment by OACDesigns** [comment]
great, thanks!

**Comment by OACDesigns** [comment]
just discovered the minified `jsqrcode-combined.js` encounters an error as it needs to be minified in a specific order.
I've created a new pull request to fix this, along with a new working minified `jsqrcode-combined.js`

**Pull request merged**
